statistics:
  ttlInSeconds: 60
  slotSizeInMilliSeconds: 1000

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
      jmx:
        exposure:
          exclude: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always

# Swagger properties
api-documentation:
  title: 'Real time Transaction Statistics API'
  description: 'The main use case for the API is to calculate realtime statistics for the last 60 seconds of transactions'